# Site settings
baseurl = "/"
themesDir = "./themes"
languageCode = "en-us"
title = "🤠 McDonald"
theme = "hugo-privacy-cactus-theme"
enableRobotsTXT = true

[params]
	name = "🤠 McDonald"
	description = "100% human now made with extra human sauce"
	bio = "Developer"
	enableRSS = true

	# Integrate Javascript files or stylesheets by adding the url to the external assets or by
	# linking local files with their path relative to the static folder, e.g. "css/styles.css"
	customCSS = []
	customJS  = []

	# The variables below are optionally too and can be used to
	# translate or customize each string of the theme.

	# Navigation links
	home = ""
	subscribe = ""
	# Pagination links
	olderPosts = ""
	newerPosts = ""
	readMore = ""
	copyright = ""
	# 404 page
	title404 = ""
	subtitle404 = ""

	# Choose a font for the social icons in the footer. Either "mono-social" or "font-awesome"
	iconFont = "font-awesome"
    # The social icons can be styled differently if you use mono as font - circle, rounded, or empty
    socialIconStyle = ""

[social]
	facebook-square = "https://www.facebook.com/🤠mcdonald"
	twitter-square = "https://www.twitter.com/🤠wmcdonald"
	instagram = "https://www.instagram.com/🤠_.m"
	lastfm-square = "https://www.last.fm/user/🤠mcdonald"
	github-square = "https://www.github.com/🤠mcdonald"

[[menu.main]]
    name = "About"
    identifier = "About"
    url = "/about/"
