baseURL: /
theme: "hugo-theme-codex"
title: Cory McDonald
paginate: 7
googleAnalytics: ""      # UA-XXXXXXXX-X
permalinks:
  posts: /:year/:month/:filename/

markup:
  markup.highlight:
    codeFences: false

  # Set to false to disallow raw HTML in markdown files
  markup.goldmark.renderer:
      unsafe: true

outputs:
    home: ["HTML","RSS"]  # recommend not to modify
# sitemap
sitemap:
  changefreq: monthly
  filename: sitemap.xml
  priority: 0.5

menu:
  main:
    - identifier: home
      name: Home
      title: Home
      url: /
      weight: 1

    - identifier: archives
      name: Archives
      title: Archives
      url: /posts
      weight: 2

    - identifier: categories
      name: Categories
      title: Categories
      url: /categories
      weight: 3

    - identifier: tags
      name: Tags
      title: Tags
      url: /tags
      weight: 4

    - identifier: about
      name: About
      title: About
      url: /about
      weight: 5


params:
  since: 2017
  dateFormatToUse: "Jan 2 2006"
  iconTitles: ["Twitter", "GitHub"]
  github: https://github.com/corymcdonald
  twitter: https://twitter.com/corywmcdonald
